### PR TITLE
added more verbose error message to httr::stop_for_status

### PR DESCRIPTION
**Pull request by EdJeeOnGitHub**
Returns Dataverse API error message to make debugging easier.

- R CMD Check passes locally with the change.

### CODE REVIEW

**Comment by EdJeeOnGitHub** [comment]
I opened an issue [here](https://github.com/IQSS/dataverse-client-r/issues/31) with a bit more detail.

**Comment by wibeasley** [comment]
@EdJeeOnGitHub, I haven't forgotten about this PR.  I see that some of the master branch has changed since your modification, and I'll do my best to make sure you get credit.

Will you please

1. add yourself to the [DESCRIPTION](https://github.com/IQSS/dataverse-client-r/blob/master/DESCRIPTION) file as a "ctb".  Add your ORCID id if you have one.
1. update [NEWS.md](https://github.com/IQSS/dataverse-client-r/blob/master/NEWS.md) to reflect this improvement?

I'm using [R Packages](http://r-pkgs.had.co.nz/description.html#author) for the definition/distinction between the "aut" and "ctb".

**Comment by EdJeeOnGitHub** [comment]
I think I managed to fix the conflicts too?

**Comment by kuriwaki** [comment]
I like this feature very much. (See below for a reprex).

Your current IPA example fails to give the intended error (i.e. it actually passes without any error messages) because in #39 we bypassed query when the targetwas not a `.tab` file (4d45330).  That was a stopgap and should be revisited... in the meantime, are there any examples of `.tab` files for which we'd get an informative error message?  We can put that in a testthat too.

``` r
# Get `ReadMe with Codebook.docx` (https://doi.org/10.7910/DVN/JGLOZF/GYZ7OQ, id = 2972336)
# master branch
library(dataverse)
get_file(2972336, server = "demo.dataverse.org") # wrong server
#> Error in get_file(2972336, server = "demo.dataverse.org"): Not Found (HTTP 404).
```

``` r
# EdJeeOnGitHub fork branch
library(dataverse)
get_file(2972336, server = "demo.dataverse.org") # wrong server
#> Error in get_file(2972336, server = "demo.dataverse.org"): Not Found (HTTP 404). Failed to API endpoint does not exist on this server. Please check your code for typos, or consult our API guide at http://guides.dataverse.org..
```

<sup>Created on 2020-12-28 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by kuriwaki** [comment]
I like this simple addition and support working to merging this PR. I added a testthat case. See also my comment https://github.com/IQSS/dataverse-client-r/issues/31#issuecomment-751801537 on the associated Issue that seeks to find one more informative test that is compatible with current master version.

**Comment by kuriwaki** [comment]
Also, shouldn't we implement the same change in the dozens of other places where `httr::stop_for_status` is called  -- not just in `get_file()`?

**Pull request merged**
