### PR TITLE
* Missing json decoding of response for dataset_versions

### PR DESCRIPTION
**Pull request by billy34**
Should solve issue #27

### CODE REVIEW

**Comment by wibeasley** [comment]
@billy34, thanks for noticing this in #27 and filing this PR.  Because I'm new to this package, I'm reluctant to accept any PRs without an accompanying test.  And unfortunately we haven't developed a test suite that's easy for others to add a few tests with a PR of a new feature/correction like yours.

I'd like to add at least a minimal test suite that incorporates this, but realistically that might be a few weeks (see #29).

@pdurbin, @leeper, or anyone else, I don't want to delay @billy34's contribution unnecessarily.  Please accept the PR if you'd like.

**Comment by pdurbin** [comment]
@wibeasley I'm fully supportive of #29 and the issues you linked there: #4 and #22

You are completely sane to want tests in place before merging pull requests. :smile: 

@billy34 thanks for the pull request! As the brand new maintainer of dataverse-client-r (thanks again!) @wibeasley has inherited a ton of code so please be patient as he comes up to speed and gets comfortable. :smile: If you have any thoughts on adding tests, please let us know!

**Comment by wibeasley** [comment]
@billy34 , I haven't forgotten about this PR.  

Will you please

1. add yourself to the [DESCRIPTION](https://github.com/IQSS/dataverse-client-r/blob/master/DESCRIPTION) file as a "ctb".  Add your ORCID id if you have one.
1. update [NEWS.md](https://github.com/IQSS/dataverse-client-r/blob/master/NEWS.md) to reflect this improvement?

I'm using [R Packages](http://r-pkgs.had.co.nz/description.html#author) for the definition/distinction between the "aut" and "ctb".

**Comment by wibeasley** [comment]
@billy34, thanks for this.  I see that the Travis error are coming from some breaking change in the covr prereq, and nothing to do with your code (or even the package's code).

**Comment by kuriwaki** [comment]
@billy34: I fixed unmatched parenthesis in the author listing that were preventing the package from compiling. Anyhow, after that the `package_versions` don't work. Maybe it's due to changes introduced since your PR. Do these two reprex examples below work for you?

``` r
## load package
library("dataverse")

## set server internally
Sys.setenv("DATAVERSE_SERVER" = "dataverse.harvard.edu")

# 1. from help page of dataset_versions
monogan <- get_dataverse("monogan")
monogan_data <- dataverse_contents(monogan)
d1 <- get_dataset(monogan_data[[1]])
dataset_versions(d1)
#> Error in dataset_versions(d1): Not Found (HTTP 404).

# 2. from another simple example on DEMO
d1 <- get_dataset(dataset = "doi:10.70122/FK2/PPKHI1",
               server = "demo.dataverse.org")
class(d1)
#> [1] "dataverse_dataset"
dataset_versions(d1, server = "demo.dataverse.org")
#> Error in dataset_versions(d1, server = "demo.dataverse.org"): Not Found (HTTP 404).
```

<sup>Created on 2020-12-28 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by kuriwaki** [comment]
I don't know JSON as well but it seems 0dc86ca has the same effect as the proposed JSON edit here and is simpler.

**Pull request closed without merging**
