### PR TITLE
Simplify and update vignettes

### PR DESCRIPTION
**Pull request by kuriwaki**
This PR makes updates to vignettes for v0.3.x+.  They had not been updated since v0.2.0. 

- Add explanations about `get_dataframe_*` with different files, explaining the arguments
- Slim down -- remove references to dvn, sword, and UNF, as these seem not used now.
- Remove article about data upload, given the outstanding errors (#20,  #23, #82 etc..)

### CODE REVIEW

**Comment by Danny-dK** [comment]
Are you sure you want to remove the sword references? For now that's the only way that I am able to upload datasets. #82

**Comment by kuriwaki** [comment]
@Danny-dK I missed that sword does work (I was trying to remove parts that have any problems). If you have any updates to that issue, that'll be great when I take a look today. 

We included informative error messages in the latest master version (#30)

**Comment by Danny-dK** [comment]
@kuriwaki No worries. I added a summary in #82 of the code that now works and what doesn't work (as it was indeed getting a bit much in unstructured information).

**Comment by kuriwaki** [comment]
I updated the part of the README with your example (with eval = FALSE). It is similar to the archiving vignette that was deleted and can be added back. 

But given that this is a workaround and there are some questions (e.g. the workaround a mixup of SWORD vs. native API), I'd rather publish a version for which all examples work.  The fixes to the the uploading is perhaps a 0.4.0 milestone or pyDataverse task. 

@wibeasley what do you think?

**Comment by wibeasley** [comment]
Looks good, @kuriwaki & @Danny-dK, thanks for keeping all the parts straight.

**Pull request merged**
